version: "2"

services:
  ipa:
    image: freeipa/freeipa-server:rocky-9-4.10.1
    container_name: ipa
    hostname: ipa.vehant.edu
    restart: always
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "ipa-data:/data"
    environment:
      - PASSWORD=StrongPassw0rd
      - IPA_SERVER_IP=172.16.30.2
    command: ipa-server-install --domain vehant.edu --realm VEHANT.EDU --reverse-zone=0.24.172.in-addr.arpa --no-forwarders --no-ntp --setup-dns --ds-password StrongPassw0rd --admin-password StrongPassw0rd --unattended
    ports:
      - "453:53"
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "453:53/udp"
      - "464:464/udp"
    networks:
      ipa_network:
        ipv4_address: 172.24.0.3
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      
networks:
  ipa_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
          aux_addresses:
            dns: 172.24.0.2

volumes:
  ipa-data:
